services:
  backend:
    build: backend
    expose:
      - "4000"
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=a.noboroto.id.vn
      
  frontend:
    depends_on:
      - backend
    build: frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=fire.noboroto.id.vn
