services:
  frontend:
    build: frontend
    expose:
      - "80"
    restart: unless-stopped
    ports:
      - "8266:80"
    environment:
      - VIRTUAL_HOST=fire.noboroto.id.vn
      - VIRTUAL_PORT=80
    networks:
      - proxynet

networks:
  proxynet:
    external:
      name: proxy_net
